### ISSUE TITLE
GNOME 46 Support

### ISSUE THREAD

**Issue by kzhe2059** [PolyMeilex/gnome-shell-extension-panel-workspace-scroll#1]
Please add support for GNOME 46

**Comment by PolyMeilex** [comment]
Sure, do you known if it works already if you disable version guards? (aka.  `gsettings set org.gnome.shell disable-extension-version-validation "true"`)

If so I can just bump the version and releasse, if not I will have to take some time to setup a dev enviroment for G46 to test it (as I'm still on 45 atm)

**Comment by PolyMeilex** [comment]
Ok, it works as expected in my GNOME 46 VM, will release soon
